ami: ami-f1d7c395
region: eu-west-2
subnet: subnet-b516cbce
sg: szkolenie-security-group
key: szkolenie_05_london
ansible_ssh_private_key_file: '~/.ssh/szkolenie_05_london.pem'
location: london
assign_public_ip: True
ec2_url: "https://ec2.eu-west-2.amazonaws.com"
