- hosts: naszaaplikacja

  become: true

  vars:
    katalog_glowny: /var/www/szkolenie
    katalog_aplikacji: "{{ katalog_glowny }}/aplikacja"
    log_dir: "{{ katalog_glowny }}/logs"
    port: 5081

  tasks:
    - name: 'zainstaluj aplikacje apache2 i libapache2-mod-wsgi przekazując listę'
      apt: 
        pkg:
          - apache2
          - libapache2-mod-wsgi

    - name: 'zainstaluj aplikacje apache2 i pozostale pakiety przy pomocy with_items'
      apt: 
        name: "{{ item }}"
      loop:
        - apache2
        - libapache2-mod-wsgi
          #- libapache2-mod-wsgi-py3 #dla python3
        - python-dev

    - git:
        repo: https://github.com/sirkubax/naszaaplikacja.git
        dest: "{{ katalog_glowny }}"
        force: yes
      name: 'klonuj repozytorium aplikacji'
      notify: restart apache

    - pip: 
        requirements: "{{ katalog_aplikacji }}/requirements.txt"
        virtualenv: "{{ katalog_aplikacji }}/venv"
      name: 'zainicjalizuj virtualenv i zainstaluj zaleznosci' 

    - name: 'wgraj definicje virtualhost naszaaplikacja.apache.conf jako template'
      template:
          src: naszaaplikacja.apache.conf
          dest: /etc/apache2/sites-available/
      backup: True
      notify: restart apache

    - name: 'konfiguruj apache do nasluchiwania na wybranym porcie'
      lineinfile: 
        dest: /etc/apache2/ports.conf
        line: "Listen {{ port }}"
        regexp: "^Listen {{ port }}"
      notify: restart apache
  
    - name: 'wlacz virtualhost'
      shell: a2ensite {{ item }}
      args:
        creates: /etc/apache2/sites-enabled/{{ item }}
      loop: 
        - naszaaplikacja.apache.conf
      notify: restart apache

    - name: 'Wgraj sparametryzowany naszaaplikacja.wsgi (jako template)'
      template:
          src: naszaaplikacja.wsgi
          dest: "{{ katalog_aplikacji }}"
      backup: True
      notify: restart apache

    - name: 'Wgraj sparametryzowany config.cfg (jako template)'
      template:
          src: config.cfg
          dest: "{{ katalog_aplikacji }}"
      backup: True
      notify: restart apache

    - name: 'utworz katalog na logi'
      file:
        state: directory
        path: "{{ log_dir }}"
        owner: www-data
        group: www-data
        mode: 0755

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      notify: 
        - Wait for instances to listen on port 80
        - Wait for instances to listen on port 5081
#        - Wait for instances to listen on port naszaaplikacja

    - name: Wait for instances to listen on port 80
      wait_for: 
        state: started 
        host: localhost 
        port: 80 
        timeout: 15 
        delay: 5

    - name: Wait for instances to listen on port 5081
      wait_for: 
        state: started 
        host: localhost 
        port: "{{ port }}"
        timeout: 15 
        delay: 5

#    - name: Wait for instances to listen on port naszaaplikacja
#      wait_for: 
#        state: started 
#        host: localhost 
#        port: "{{ port }}"
#        timeout: 15 
#        delay: 5
