---
#Uruchomienie:
#~/szkolenie$ ansible-playbook playbooks/configure_apache.yml

- hosts: apache

  vars:
      apache2_log_level: "info"

  handlers:
  - name: restart apache
    service: 
      name: apache2
      state: restarted
      enabled: True
    notify: 
      - Wait for instances to listen on port 80
    become: True

  - name: reload apache
    service: 
      name: apache2
      state: reloaded
    notify: 
      - Wait for instances to listen on port 80
    become: True

  - name: Wait for instances to listen on port 80
    wait_for: 
      state: started 
      host: localhost 
      port: 80 
      timeout: 15 
      delay: 5

  tasks:
  - name: Update cache 
    apt: update_cache=yes cache_valid_time=7200
    become: True

  - name: Install packages
    apt: name={{ item }}
    with_items:
      - apache2
    notify:
      - restart apache
    become: True

  - name: configure apache2 log level
    lineinfile: 
      dest: /etc/apache2/apache2.conf
      line: "LogLevel {{ apache2_log_level }}"
      regexp: "^LogLevel"
    notify:
      - reload apache
    become: True

